name: Publish package

on:
  release:
    types:
      - released
      - prereleased

jobs:
  build:
    name: Build distribution packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install build --user
      - name: Build
        run: python -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package
          path: dist/

  github-release:
    name: Sign the distribution packages and upload them to GitHub Release
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Mandatory for making GitHub Releases
      id-token: write  # Mandatory for sigstore
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package
        path: dist/
    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v1.2.3
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: gh release upload '${{ github.ref_name }}' dist/** --repo '${{ github.repository }}'

  publish-to-pypi:
    name: Publish distribution packages to PyPI
    if: |
      startsWith(github.ref, 'refs/tags/') &&
      !github.event.release.prerelease
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/python-logging-rabbitmq
    permissions:
      id-token: write  # Mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package
        path: dist/
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-testpypi:
    name: Publish distribution packages to TestPyPI
    if: |
      startsWith(github.ref, 'refs/tags/') &&
      github.event.release.prerelease
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/python-logging-rabbitmq
    permissions:
      id-token: write  # Mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package
        path: dist/
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
